# Generated by Django 5.0.12 on 2025-04-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boulder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('grade', models.CharField(max_length=255, verbose_name='Grade')),
                ('style', models.CharField(max_length=255, verbose_name='Style')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('photo', models.ImageField(null=True, upload_to='boulders', verbose_name='Photo')),
                ('segmented_image', models.ImageField(null=True, upload_to='boulders', verbose_name='Segmented Image')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Private')),
            ],
        ),
    ]
