# Generated by Django 5.1.6 on 2025-02-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('brand', models.CharField(max_length=255, verbose_name='Brand')),
                ('equipment_type', models.CharField(max_length=255, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('photo', models.ImageField(blank=True, upload_to='equipment', verbose_name='Photo')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Private')),
            ],
        ),
    ]
